---
title: "GenBank_Data"
author: "Biancani"
date: "April 8, 2016"
output: pdf_document
---
#Download Data from GenBank:

##Entrez Direct (EDirect) Installation
http://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Getting_Started

At UNIX command line, enter:
```{bash, eval=FALSE}
cd ~
perl -MNet::FTP -e \
'$ftp = new Net::FTP("ftp.ncbi.nlm.nih.gov", Passive => 1); $ftp->login;
$ftp->binary; $ftp->get("/entrez/entrezdirect/edirect.zip");'
unzip -u -q edirect.zip
rm edirect.zip
export PATH=$PATH:$HOME/edirect
./edirect/setup.sh
```

##Use EDirect to Download Fasta & GenBank Files

At UNIX command line enter:
```{bash, eval=FALSE}
# specify options for fasta files:
#TAXA=scinidae; DATABASE=popset; FORMAT=fasta
#TAXA=hyperia; DATABASE=nucleotide; FORMAT=fasta

TAXA=Hyperiidea; DATABASE=nucleotide; FORMAT=fasta



#TAXA=Gammaridea; DATABASE=nucleotide; FORMAT=fasta
#TAXA=Ingolfiellidea; DATABASE=nucleotide; FORMAT=fasta

TAXA=Senticaudata; DATABASE=nucleotide; FORMAT=fasta #too large?

##subgroups of Senticaudata:
#TAXA=Bogidiellida; DATABASE=nucleotide; FORMAT=fasta
#TAXA=Corophiida; DATABASE=nucleotide; FORMAT=fasta
##TAXA=Gammarida; DATABASE=nucleotide; FORMAT=fasta #error fixed, okay now
#TAXA=Hadziida; DATABASE=nucleotide; FORMAT=fasta #downloaded, not run yet
#TAXA=Talitrida; DATABASE=nucleotide; FORMAT=fasta #not downloaded yet
#TAXA=unclassified Senticaudata

TAXA=hyperia; DATABASE=nucleotide; FORMAT=fasta


QUERY=$TAXA"[ORGN] NOT Environmental samples[ORGN]"
#NOT Environmental samples eliminates 20 sequences in Amphipoda

FILENAME=$DATABASE.$TAXA.$FORMAT
esearch -db $DATABASE -query $QUERY | efetch -format $FORMAT > $FILENAME

#options to change for genbank files:
FORMAT=gb

FILENAME=$DATABASE.$TAXA.$FORMAT
esearch -db $DATABASE -query $QUERY | efetch -format $FORMAT > $FILENAME

echo $TAXA.downloaded!



```




##Read Data into R

```{r}
#specify options used above for EDirect:
#TAXA="scinidae"
#TAXA="hyperia"

#TAXA="Amphipoda"

#TAXA="Hyperiidea"
#TAXA="GammarideaIngolfiellidea"
#TAXA="Senticaudata"


#TAXA="Gammaridea"
#TAXA="Ingolfiellidea"
##TAXA="Senticaudata"
#TAXA="Bogidiellida"
#TAXA="Corophiida"

#TAXA="Gammarida"


#TAXA="Hadziida"
#TAXA="Talitrida"

TAXA="Amphipoda5gene"

#DATABASE="popset"
DATABASE="nucleotide"

fasta_filename=paste(DATABASE,TAXA,"fasta",sep=".")
genbank_filename=paste(DATABASE,TAXA,"gb",sep=".")

#read data into R
fasta=readLines(fasta_filename)
genbank=readLines(genbank_filename)
```

##Parse Data

```{r, eval=FALSE, tidy=TRUE}
#load stringr library
library(stringr)

#create vector of genbank data
genbank_vector=c()
gb=""
for(line in genbank){
  gb=paste(gb,line,sep=" ")
  if(str_detect(line,"//")){
    gb=str_replace_all(gb," +"," ")
    genbank_vector=append(genbank_vector,gb)
    gb=""
  }
}

genelookup= data.frame(
  rawlist=c("[Cc]ytochrome [Cc ]{0,2}oxidase [subunit ]{0,8}[I1i][^1Ii]","[cC][Oo][Xx]{0,1}[1Ii][^1Ii]","12S","16S","large subunit.*mitochondrial","18S","S18","small subunit ribosomal","28S","histone [Hh]{0,1}3","RpS5","RpS2","ArgKin","EF-{0,1}1-{0,1}a","elongation factor 1[ -]a","G[aA][pP][dD][hH]","IDH","MDH","CAD","wingless","[cC][Oo][Xx]{0,1}2","[Cc][Oo][Xx]{0,1}II[^I]","[cC][Oo][Xx]{0,1}3","[Cc][Oo][Xx]{0,1}III","ATP6","cytochrome [Bb]","[hH][sS][pP]70[ )]","hsp70-2","hsp70-1","mitochondri[onal DNA,]{2,7}, complete genome","complete mitochondrial genome","mitochondri[onal DNA,]{2,7} partial genome","partial mitochondrial genome","[Ii][TtGg][Ss]","internal transcribed spacer","transposon","Unknown sequence","unknown mRNA","anonymous locus","NAK-ATPase","sodium/potassium ATPase","prostaglandin E synthase","cyclooxygenase","GH7D","GH7A","actin","Abcb1","superoxide dismutase gene","hemocyanin","ND5","ND2","CsDll","contig_\\d+_\\d+ transcribed RNA","[Mm]icrosatellite","(Rh)","myosin heavy chain","whole genome shotgun","transcriptome shotgun"),
  genelist=c("mt_COI","mt_COI","mt_12S","mt_16S","mt_16S","n_18S","n_18S","n_18S","n_28S","n_H3","n_RpS5","n_RpS2","n_ArgKin","n_EF1a","n_EF1a","n_GAPDH","n_IDH","n_MDH","n_CAD","n_Wgl","mt_COX2","mt_COX2","mt_COX3","mt_COX3","mt_ATP6","mt_CytB","n_hsp70","n_hsp70_2","n_hsp70_1","mt_Genome","mt_Genome","mt_Genome_partial","mt_Genome_partial","n_ITS","n_ITS","n_transposon","Unknown","Unknown","anonymous_locus","n_NAK_ATPase","n_NAK_ATPase","n_PTGS","n_PTGS","n_GH7D","n_GH7A","n_actin","n_Abcb1","n_MnSOD","n_hemocyanin","mt_ND5","mt_ND2","CsDll","RNAseq_contig","microsat","n_Rh","n_MHC","whole_genome_shotgun","transcriptome_shotgun")
)

#initiate vectors
fasta_header=c()
sequence=c()

species_name=c()
organism=c()
accession=c()
description=c()

voucher=c()
country=c()
isolate=c()
gene=c()
bp_length=c()
taxon_id=c()

author_ref1=c()
title_ref1=c()
journal_ref1=c()

author_ref2=c()
title_ref2=c()
journal_ref2=c()

author_ref3=c()
title_ref3=c()
journal_ref3=c()

others=c()

#parse fasta (& genbank) data
seq=""
record=0
for (i in seq(length(fasta))) {
  line = fasta[i]
  # if a header is detected:
  if (str_detect(line,fixed(">"))){
    #if sequence was recorded for previous record, add it to the sequence vector
    if (i>1) {sequence=append(sequence,seq)}
    seq="" #reset seq
    
    record=record+1 #track record number
    
    #store fasta header
    fasta_header = append(fasta_header,line)
    
    #parse fasta header
    header_split=strsplit(line, "|", fixed=TRUE)
    
    #accession from fasta
    accession=append(accession,header_split[[1]][4])
    
    #description from fasta
    des=str_trim(header_split[[1]][5], side="left")
    description=append(description,des)
    
    #species name from fasta
    #[cfa. ]{0,5} added to accomodate "Genus cf. species" and "Genus aff. species"
    species_name=append(species_name,str_extract(des,"[A-Z][a-z]*[ .][cfa. ]{0,5}[a-z.]+"))
    
    #gene from fasta
    ingenes=FALSE
    gen=""
    for(i in seq(length(genelookup$rawlist))){
      if(str_detect(des,as.character(genelookup$rawlist[i]))){
        lookup=as.character(genelookup$genelist[i])
        if(!str_detect(gen,lookup)){gen=paste(lookup,gen,sep=" ")}
        ingenes=TRUE
      }
    }
    if(!ingenes){
      gen = "other"
      others=append(others,des)
    }
    gene=append(gene,gen)
    
    
    
    #parse data from genbank file:
    gb=genbank_vector[record]
    
    #organism from gb
    org_pattern="organism=\"([^\"]+)\""
    org=str_replace(str_extract(gb,org_pattern),org_pattern,"\\1")
    organism=append(organism,org)
    
    #voucher number from gb
    vou_pattern="voucher=\"([^\",]*\\d[^\",]*)\""
    vou=str_replace(str_extract(gb,vou_pattern),vou_pattern,"\\1")
    voucher=append(voucher,vou)
    
    #country from gb
    country_pat="country=\"([^\"]+)\""
    coun=str_replace(str_extract(gb,country_pat),country_pat,"\\1")
    country=append(country,coun)
    
    #isolate number from gb
    iso_pattern="/isolate=\"([^\"]+)\""
    iso=str_replace(str_extract(gb,iso_pattern),iso_pattern,"\\1")
    isolate=append(isolate,iso)
    
    #sequence length from gb
    bps=as.numeric(str_extract(str_extract(gb,"[:digit:]+ bp"),"[:digit:]+"))
    bp_length=append(bp_length,bps)
    
    #taxon ID from gb
    tax=as.numeric(str_extract(str_extract(gb,"taxon:[:digit:]+"),"[:digit:]+"))
    taxon_id=append(taxon_id,tax)
    
    #author and/or consortium for References 1-3 from gb
    reference_ends=c("REFERENCE","COMMENT","FEATURES")
    for(end in reference_ends){gb=str_replace_all(gb,end,paste("@",end,sep=""))}
    reference_keys=c("AUTHORS","CONSRTM","TITLE","JOURNAL")
    for(key in reference_keys){gb=str_replace_all(gb,key,paste("%",key,sep=""))}
    
    #REFERENCES 1-3
    for (i in 1:3) {
      auth_pat=paste("REFERENCE ","[^@]+%AUTHORS ([^%]+) %",sep=as.character(i))
      cons_pat=paste("REFERENCE ","[^@]+%CONSRTM ([^%]+) %",sep=as.character(i))
      title_pat=paste("REFERENCE ","[^@]+%TITLE ([^%]+) %",sep=as.character(i))
      journ_pat=paste("REFERENCE ","[^@]+%JOURNAL ([^%@]+) [%@]",sep=as.character(i))
      auth= str_replace(str_extract(gb,auth_pat),auth_pat,"\\1")
      cons= str_replace(str_extract(gb,cons_pat),cons_pat,"\\1")
      title= str_replace(str_extract(gb,title_pat),title_pat,"\\1")
      journ= str_replace(str_extract(gb,journ_pat),journ_pat,"\\1")
      if(is.na(auth)){
        auth=cons # in case consortium listed but no author
      }else if(!is.na(cons)){
        auth=paste(auth,cons,sep=", ") # in case author & consortium listed (never?)
      }
      if(i==1){
        author_ref1=append(author_ref1,auth)
        title_ref1=append(title_ref1,title)
        journal_ref1=append(journal_ref1,journ)
      }else if(i==2){
        author_ref2=append(author_ref2,auth)
        title_ref2=append(title_ref2,title)
        journal_ref2=append(journal_ref2,journ)
      }else if(i==3){
        author_ref3=append(author_ref3,auth)
        title_ref3=append(title_ref3,title)
        journal_ref3=append(journal_ref3,journ)
      }
    }
    
  } else {
    # if the line is not a header, add the line to seq
    seq=paste(seq,line,sep="")
  }
}
sequence=append(sequence,seq)

df=data.frame(species_name,organism,taxon_id,voucher,isolate,country,accession,gene,bp_length,author_ref1,title_ref1,journal_ref1,author_ref2,title_ref2,journal_ref2,author_ref3,title_ref3,journal_ref3,description,fasta_header,sequence,stringsAsFactors=FALSE)

print(others)

```

##Build Gene Table

```{r, eval=FALSE, tidy=TRUE}


genelist=(unique(as.character(genelookup$genelist)))

#initialize gene vectors:
for(gene in genelist) {assign(gene,c())}

g=""
for(i in seq(nrow(df))){
  entry=as.character(df$gene[i])
  for(gene in genelist){
    if(str_detect(entry,gene)){g=df$accession[i]}
    assign(gene,do.call(append,list(as.name(gene),g)))
    g=""
  }
}

gene_table=df[,c(2:4,10)]
gene_table=data.frame(gene_table,do.call(cbind,lapply(genelist,as.name)),stringsAsFactors = FALSE)

#aggregate rows where voucher # matches (omits rows where voucher is NA)
gt=aggregate(gene_table, by=list(gene_table$voucher), max, na.rm=TRUE)

#remove Group.1 row
gt=gt[,c(2:ncol(gt))]

#replace rows where voucher is NA
gt=rbind(gt,gene_table[is.na(voucher),])
```

##Output Data

```{r, eval=FALSE, tidy=TRUE}
#parsed data table
df_filename=paste(TAXA,DATABASE,"alldata.txt",sep=".")
write.table(df, df_filename, sep="\t",row.names=FALSE)
#gene table
gt_filename=paste(TAXA,DATABASE,"genetable.txt",sep=".")
write.table(gt, gt_filename, sep="\t",row.names=FALSE)

```
